version: "3.3"

#MS-SQL Server
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  sql:
    hostname: sql
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=yes
      - SA_PASSWORD=Pass@word1
    restart: always

  zookeeper:
    hostname: zookeeper
    image: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    restart: unless-stopped

  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=${HOST_NAME}:2181,${HOST_NAME}:2888,${HOST_NAME}:3888
      - KAFKA_ADVERTISED_HOST_NAME=${HOST_NAME}
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      - KAFKA_ADVERTISED_PROTOCOL_NAME=INSIDE
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=100
      - KAFKA_LISTENERS=INSIDE://:9092,OUTSIDE://:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    depends_on: 
      - zookeeper
    restart: unless-stopped
    
  kafka-manager:
    hostname: kafka-manager
    image: sheepkiller/kafka-manager
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=${HOST_NAME}:2181,${HOST_NAME}:2888,${HOST_NAME}:3888
    restart: unless-stopped
    depends_on: 
      - zookeeper
      - kafka

